services:
  kerigma_app_dev:
    container_name: kerigma_app_dev
    image: ggsheet/kerigma_app_dev:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    env_file:
      - .env.docker.dev
    ports: 
      - "8080:8080"
    volumes:
      - ./:/app
    depends_on:
      - kerigma_db_dev

  kerigma_db_dev:
    container_name: kerigma_db_dev
    image: postgres:16
    env_file:
      - .env.docker.dev
    ports:
      - "5432:5432"
    volumes:
      - pgdata_dev:/var/lib/postgresql/data

volumes:
  pgdata_dev:
